### ISSUE TITLE
Make `download` an optional feature

### ISSUE THREAD

**Issue by Gowee** [DevQps/rsef-rs#2]
Hi. 

`fn download` uses several non-trivial third-party crates including `reqwest`, `bzip2` and `libflate` to download stats from RIR. It is convenient and helpful in many circumstances.

However, as a library, it is sometimes more desirable to be as minimal as possible from the perspective of users.

So I propose to make the `download` function [an optional feature](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) with conditional compilation configured.

How do you think?

**Comment by DevQps** [comment]
@Gowee Sorry for my ultra late response. For some reason I never got any notification of this...
I think that is better as well! Maybe we could put it behind a feature flag `download` or something? Or `reqwest`. Which do you think is better?

**Comment by Gowee** [comment]
No problem. Actually, it is a pleasant surprise to see your reply so long later because I almost forget this issue. 

Both `download` and `reqwest` looks fine. And how about `datasource` or other nouns? As a non-native English speaker, I have no feeling about which one is more appropriate.

**Comment by DevQps** [comment]
Thank you for your reply! I will try to implement this as soon as I can!

**Comment by DevQps** [comment]
@Gowee I created a PR for this!: #3 

What do you think?

**Comment by Gowee** [comment]
@DevQps Looks good to me. Thanks.

The only improvement I can propose is to return `Iterator<Item=Line>` instead of `Vec<Line>`. 
But the RSEF file would not be too large in practice. And Rust's [generator](https://doc.rust-lang.org/beta/unstable-book/language-features/generators.html) has not been stable, it is not ergonomic to write an `Iterator` manually. So the additional abstraction may neither be necessary nor worth it.

**Comment by DevQps** [comment]
Ahh that sounds good indeed. I will take a look at it! Sorry for the slow response. I had some private things that took up a lot of time :) I hope to finish these things next Wednesday.

**Comment by DevQps** [comment]
@Gowee I made some changes and added the return type for Iterator. If you have some spare time I would be happy if you could give a quick look at it! If you find it good like this, I will merge it and bump the version on crates.io to 0.2.0
